# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -direct" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded xdobry::access 0.62 [list source [file join $dir xdobry_access.xotcl]]
package ifneeded xdobry::mssql 0.1 [list source [file join $dir xdobry_mssql.xotcl]]
package ifneeded xdobry::mysql 0.61 [list source [file join $dir xdobry_mysql.xotcl]]
package ifneeded xdobry::odbc 0.62 [list source [file join $dir xdobry_odbc.xotcl]]
package ifneeded xdobry::oratcl 0.1 [list source [file join $dir xdobry_oratcl.xotcl]]
package ifneeded xdobry::pgsql 0.604 [list source [file join $dir xdobry_pgsql.xotcl]]
package ifneeded xdobry::sql 0.63 [list source [file join $dir xdobry_sql.xotcl]]
package ifneeded xdobry::sqlite 0.61 [list source [file join $dir xdobry_sqlite.xotcl]]
